[package]
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
name = "gif-dispose"
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Implements GIF disposal method for the gif crate. The gif crate only exposes raw frame data that is not sufficient to render GIFs properly. GIF requires special composing of frames which, as this crate shows, is non-trivial."
keywords = ["gif", "frames", "animation"]
documentation = "https://docs.rs/gif-dispose/"
homepage = "https://github.com/kornelski/image-gif-dispose#readme"
repository = "https://github.com/kornelski/image-gif-dispose.git"
categories = [ "multimedia::video", "multimedia::images" ]
version = "2.1.1"

[dependencies]
gif = "0.10.0"
imgref = "1.3.0"
rgb = "0.8.9"
